---
# Setup/install tasks.
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed
  apt: "name={{ apache_packages }} state=present"

- name: create logicdesk_root_dir
  file:
    path: "{{ logicdesk_root_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
    
- name: clone a private repository
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@{{ logicdesk_repo }}"
    dest: "{{logicdesk_root_dir}}"
    version: "re-build"
    update: no

# PHP requires specific permissions on files and directories
- name: Register all directories downloaded
  find:
    path: "{{logicdesk_root_dir}}"
    file_type: directory
    recurse: yes
  register: find_directory

- name: Change owner/permission of found directories
  file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: 0755
  with_items: "{{ find_directory.files }}"

- name: Register all files downloaded
  find:
    path: "{{logicdesk_root_dir}}"
    file_type: file
    recurse: yes
  register: find_files

- name: Change owner/permission of found files
  file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ find_files.files }}"

# Configure Apache.
- name: Configure Apache.
  lineinfile:
    dest: "/etc/apache2/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Enable Apache mods.
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "/etc/apache2/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ apache_vhosts_filename }}"
    dest: "/etc/apache2/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "/etc/apache2/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "apache2"
    state: "started"
    enabled: true

- name: Setup database connection config
  lineinfile:
    dest: "{{logicdesk_root_dir}}config.php"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items: "{{ db_connection_settings }}"
  notify: reload apache
  # no_log: True

