---

- name: Set hostname for server
  hostname:
    name: "{{ inventory_hostname }}"
  with_items: "{{ groups.all }}"  

- name: Add IP address of all hosts to all hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}"
    insertafter: EOF
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"
